config:
  debug: false

  lang: "en"

  host: localhost
  port: 9051
  server-key: "key"

  voice: 
    proximity-distance: 30
    proximity-toggle: true
    voice-effects: true

    not-in-voice-symbol: "\u2727"
    in-voice-symbol: "\u2726"

  players:
    AlphaBaqpla: "228"